---

# - name: Add Mullvad repo
#   ansible.builtin.yum_repository:
#     name: mullvad
#     description: Mullvadd YUM repo
#     baseurl: https://repository.mullvad.net/rpm/stable/mullvad.repo

- name: Install wget Package
  ansible.builtin.dnf:
    name: wget # "https://github.com/mullvad/mullvadvpn-app/releases/download/2025.4/MullvadVPN-2025.4_x86_64.rpm"
    state: present

- name: Download Mullvad rpm
  ansible.builtin.get_url:
    dest: /tmp/mullvad.rpm
    url: https://github.com/mullvad/mullvadvpn-app/releases/download/2025.4/MullvadVPN-2025.4_x86_64.rpm
    mode: 0755

- name: Install Mullvad Package
  ansible.builtin.command: dnf install -y /tmp/mullvad.rpm
  args:
    creates: /bin/mullvad

- name: Set Mullvad Account
  ansible.builtin.command: mullvad account set {{ mullvad_acct }}

- name: Set Mullvad relay
  ansible.builtin.command: mullvad relay set location us qas

- name: Allow Mullvad LAN access
  ansible.builtin.command: mullvad lan set allow

- name: Set auto connect
  ansible.builtin.command: mullvad auto-connect set on

- name: Connect
  ansible.builtin.command: mullvad connect

- name: Set killswitch on
  ansible.builtin.command: mullvad always-require-vpn set on

- name: Remove Mullvad Download
  ansible.builtin.file:
    path: /tmp/mullvad.rpm
    state: absent
