---
- name: Install Mullvad VPN
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - vars/group_vars.yml
  vars:
    ansible_python_interpreter: /root/.pyenv/shims/python
  tasks:
    - name: Install Mullvad
      ansible.builtin.apt:
        deb: https://mullvad.net/download/app/deb/latest
        state: present
      tags: install

