---

- name: Add Mullvad repo
  ansible.builtin.yum_repository:
    name: mullvad
    description: Mullvadd YUM repo
    baseurl: https://repository.mullvad.net/rpm/stable/mullvad.repo

- name: Install Mullvad Package
  ansible.builtin.dnf:
    name: mullvad-vpn
    state: present
    repo: mullvad