---
- name: Media Manager
  hosts: manager
  vars_files:
    - vars/group_vars.yml
  post_tasks:
    - name: Create Media Mount Point
      command: mkdir -p /Media

    - name: Mount Media Share
      mount:
        path: /Media
        src: 192.168.1.33:/mnt/user/Media
        fstype: nfs
        opts: _netdev,defaults,auto,noatime,nofail,x-systemd.automount
        state: mounted
  roles:
    - epel
    - pip
    - docker
    - docker-compose
    - media-manager

