---
- name: Media Manager
  hosts: manager
  vars:
    ansible_ssh_user: root
#    ansible_ssh_pass: blu2013!
  post_tasks:
    - name: Create Media Mount Point
      command: mkdir -p /Media

    - name: Mount Media Share
      mount:
        path: /Media
        src: 192.168.1.33:/mnt/user/Media
        fstype: nfs
        opts: auto,noatime,nofail
        state: mounted
  roles:
    - media-manager

