---

- name: Setup rhel media manager
  hosts: ol9-mediamgr
  become: true
  vars_files:
    - vars/group_vars.yml
  tasks:
    - name: Install mullvad
      ansible.builtin.include_tasks: include-install-mullvad-ol9.yml

    - name: Setup NFS mount
      tags: mount
      block:
        - name: Install NFS utils
          ansible.builtin.dnf:
            name: nfs-utils
            state: present

        - name: Create Media Mount Point
          ansible.builtin.command: mkdir -p /Media

        - name: Mount Media Share
          ansible.posix.mount:
            path: /Media
            src: 192.168.1.33:/mnt/user/Media
            fstype: nfs
            opts: _netdev,defaults,auto,noatime,nofail,x-systemd.automount
            state: mounted

    - name: Ensure group "media" exists
      ansible.builtin.group:
        name: "{{ media_group }}"
        state: present

    - name: Include Deluge Setup
      ansible.builtin.include_tasks: include-install-deluge.yml
      tags: deluge

    - name: Include Bazarr Setup
      ansible.builtin.include_tasks: include-install-bazarr.yml
      tags: bazarr

  handlers:
    - name: Restart Deluge services
      community.docker.docker_compose_v2:
        project_src: "{{ deluge_home }}/config"
        state: restarted
      tags: restart_deluge

    - name: Restart Bazarr services
      community.docker.docker_compose_v2:
        project_src: "{{ bazarr_home }}/config"
        state: restarted
      tags:
        - restart_bazarr
        - bazarr
  roles:
    - role: geerlingguy.git
      tags: git
    - role: geerlingguy.docker
      tags: docker
    - role: geerlingguy.repo-epel
      tags: epel
