---

- name: Setup rhel media manager
  hosts: ol9-mediamgr
  become: true
  vars_files:
    - vars/group_vars.yml
  tasks:
    - name: Install mullvad
      ansible.builtin.include_tasks: include-install-mullvad-ol9.yml
  roles:
    - role: geerlingguy.git
    - role: geerlingguy.docker
    - role: totaldebug.deluge
      vars:
        enable_logging: true
        deluge_log_dir: '/var/log/deluge/'
        deluge_log_level: warning

