---

# ansible-playbook -i localhost, plex-music.yml -e upgrade=True

- name: Install Plex Docker
  hosts: manager
  gather_facts: no
  remote_user: randy
  become: yes
  vars_files:
    - vars/group_vars.yml
  roles:
    - plex-music
