---
# sudo docker run -d --name=plex --net=host -e PUID=1008 -e PGID=1008 -e VERSION=docker -v /home/plex:/config -v /Media/Music:/music --restart unless-stopped lscr.io/linuxserver/plex:latest
# ansible-playbook -i localhost, plex-music.yml -e upgrade=True

- name: Install Plex Docker
  hosts: manager
  gather_facts: no
  remote_user: randy
  become: yes
  vars_files:
    - vars/group_vars.yml
  roles:
    - plex-music
