---

# ansible-playbook -i localhost, plex-music.yml -e upgrade=True

- name: Install Plex Docker 
  hosts: all
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /root/.pyenv/shims/python
  roles:
    - plex-music
