---

- name: Install Mediainfo repo
  ansible.builtin.shell: wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-19_all.deb && dpkg -i repo-mediaarea_1.0-19_all.deb
  args:
    chdir: /tmp
  notify: Apt update

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg
    - ca-certificates

- name: Add an Apt signing key for Mono
  ansible.builtin.apt_key:
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: Add Mono repo
  ansible.builtin.shell: echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  notify: Apt update

- name: Add an Apt signing key for Sonarr
  ansible.builtin.apt_key:
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: Add Sonarr repo
  ansible.builtin.shell: echo "deb https://apt.sonarr.tv/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/sonarr.list
  notify: Apt update

- name: Add Sonarr User
  ansible.builtin.user:
    name: sonarr
    shell: /sbin/nologin

- name: Install Sonarr
  ansible.builtin.apt:
    name: sonarr
    state: present
