---

- name: Import GPG Key
  rpm_key:
    state: present
    key: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add Yum Repo
  yum_repository:
    name: mono
    description: Mono Centos Repo
    baseurl: http://download.mono-project.com/repo/centos/

- name: Install Packages
  yum:
    name: ['wget', 'nfs-utils', 'mediainfo', 'libzen', 'libmediainfo', 'curl', 'gettext', 'mono-core', 'mono-devel', 'sqlite.x86_64', 'git', 'par2cmdline', 'p7zip', 'unzip', 'tar', 'gcc', 'python-feedparser', 'python-cheetah', 'python-dbus', 'python-devel', 'libxslt-devel', 'yum-utils']
    state: latest

- name: Add Sonarr User
  user:
    name: sonarr
    shell: /sbin/nologin

- name: Create Sonarr Dir
  file:
    path: /opt/sonarr
    state: directory
    owner: sonarr
    group: sonarr

- name: Create Sonarr Bin Dir
  file:
    path: /opt/sonarr/bin
    state: directory
    owner: sonarr
    group: sonarr

- name: Download Unrar
  unarchive:
    src: https://www.rarlab.com/rar/rarlinux-x64-5.5.0.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Download Sonarr
  unarchive:
    src: https://services.sonarr.tv/v1/download/main/latest?version=3&os=linux
    group: sonarr
    owner: sonarr
    dest: /tmp
    extra_opts:
    remote_src: yes

- name: Move Sonarr Directory
  copy:
    src: /tmp/Sonarr/
    dest: /opt/sonarr/bin
    group: sonarr
    owner: sonarr
    remote_src: yes

- name: Copy Service File
  template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service

- name: Add Sonarr Port
  firewalld:
    port: 8989/tcp
    state: enabled
    permanent: yes

- name: Enable Sonarr Service
  systemd:
    name: sonarr
    daemon_reload: yes
    enabled: yes
    state: started
  notify: Reload Firewalld
