---

- name: Add Jackett User
  ansible.builtin.user:
    name: jackett
    shell: /sbin/nologin

- name: Create Jackett Dir
  ansible.builtin.file:
    path: /opt/Jackett
    state: directory
    owner: jackett
    group: jackett

#- name: Install Pre-reqs
#  yum:
#    name: libicu
#    state: present

- name: Download Jackett
  ansible.builtin.unarchive:
    src: https://github.com/Jackett/Jackett/releases/download/v0.20.1027/Jackett.Binaries.LinuxAMDx64.tar.gz
    dest: /opt/Jackett
    remote_src: yes

- name: Install Jackett
  ansible.builtin.command: ./install_service_systemd.sh
  args:
    chdir: /opt/Jackett/Jackett

- name: Copy Jackett Service File
  ansible.builtin.template:
    src: jackett.service.j2
    dest: /etc/systemd/system/jackett.service

- name: Enable Jacket Service
  ansible.builtin.systemd:
    name: jackett
    daemon_reload: yes
    enabled: yes
    state: started

- name: Add Jackett Port
  community.general.ufw:
    port: 9177
    rule: allow
    proto: tcp

- name: Cleanup Install Files
  ansible.builtin.file:
    path: /opt/Jacket/Jackett.Binaries.LinuxAMDx64.tar.gz
    state: absent