---

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ bazarr_yum_packages }}"

- name: Add Bazarr User
  user:
    name: bazarr
    shell: /sbin/nologin

- name: Create Bazarr Dir
  file:
    path: "{{ bazarr_dir }}"
    state: directory
    owner: bazarr
    group: bazarr

- name: Download bazarr
  get_url:
    url: "{{ bazarr_url }}"
    dest: /tmp
    mode: 0766

- name: Unpack Bazarr
  unarchive:
    src: "/tmp/bazarr.zip"
    group: bazarr
    owner: bazarr
    dest: "{{ bazarr_dir }}"
    extra_opts:
    remote_src: yes

- name: Copy Bazarr Service File
  template:
    src: bazarr.service.j2
    dest: /etc/systemd/system/bazarr.service

- name: Add Bazarr Port
  firewalld:
    port: 6767/tcp
    state: enabled
    permanent: yes

- name: Enable Bazarr Service
  systemd:
    name: bazarr
    daemon_reload: yes
    enabled: yes
    state: started
  notify: Reload Firewalld

- name: Cleanup Install Files
  file:
    path: "/tmp/bazarr.zip"
    state: absent
