---

- name: Install Packages
  ansible.builtin.apt:
    name: ['curl', 'sqlite3']
    state: present

- name: Add Radarr User
  ansible.builtin.user:
    name: radarr
    shell: /sbin/nologin

- name: Create Radarr Dir
  ansible.builtin.file:
    path: /opt/Radarr
    state: directory
    owner: radarr
    group: radarr

- name: Download radarr
  ansible.builtin.get_url:
    url: 'https://github.com/Radarr/Radarr/releases/download/v{{ radarr_version }}/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz' #http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
    dest: /tmp
    mode: 0766
    validate_certs: no

- name: Unpack Radarr
  ansible.builtin.unarchive:
    src: '/tmp/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz'
    group: radarr
    owner: radarr
    dest: /tmp
    extra_opts:
    remote_src: yes

- name: Move Radarr Directory
  ansible.builtin.copy:
    src: /tmp/Radarr/
    dest: /opt/Radarr
    group: radarr
    owner: radarr
    remote_src: yes

- name: Copy Service File
  ansible.builtin.template:
    src: Radarr.service.j2
    dest: /etc/systemd/system/Radarr.service

- name: Add Radarr Port
  community.general.ufw:
    port: 7878
    rule: allow
    proto: tcp

- name: Enable Radarr Service
  ansible.builtin.systemd:
    name: Radarr
    daemon_reload: yes
    enabled: yes
    state: started

- name: Cleanup Install Files
  ansible.builtin.file:
    path: '/tmp/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz'
    state: absent