---

- name: Download Nux Repo
  get_url:
    url: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    dest: /tmp
    mode: 0777

- name: Install Nux
  shell: rpm -ivh nux-dextop-release-0-5.el7.nux.noarch.rpm
  args:
    chdir: /tmp
  ignore_errors: true

- name: Install Deluge Web
  yum:
    name: deluge-web
    state: latest

- name: Install Deluge Web Service file
  template:
    src: deluge-web.service.j2
    dest: /etc/systemd/system/deluge-web.service

- name: Install Deluge Daemon Service file
  template:
    src: deluge-daemon.service.j2
    dest: /etc/systemd/system/deluge-daemon.service

- name: Enable Deluge Web
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluge-web

- name: Enable Deluge Daemon
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluge-daemon

- name: Add Deluge Firewall Rule
  firewalld:
    port: 8112/tcp
    permanent: yes
    zone: public
    state: enabled
  notify: Reload Firewalld
