---

- name: Ensure unpackerr group exists
  ansible.builtin.group:
    name: unpackerr
    state: present

- name: Add Unpackerr User
  ansible.builtin.user:
    name: unpackerr
    group: unpackerr
    shell: /bin/false
    home: /home/unpackerr

- name: Install Unpackerr
  ansible.builtin.apt:
    deb: 'https://github.com/davidnewhall/unpackerr/releases/download/v{{ unpackerr_version }}/unpackerr_{{ unpackerr_version }}-376_amd64.deb'
    state: present

- name: Install Unpackerr Config File
  ansible.builtin.template:
    src: unpackerr.conf.j2
    dest: /etc/unpackerr/unpackerr.conf

- name: Restart Unpackerr
  ansible.builtin.systemd:
    state: restarted
    name: unpackerr
