---

#- name: Download Nux Repo
#  get_url:
#    url: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
#    dest: /tmp
#    mode: 0777
#
#- name: Install Nux
#  shell: rpm -ivh nux-dextop-release-0-5.el7.nux.noarch.rpm
#  args:
#    chdir: /tmp
#  ignore_errors: true

- name: Add Deluge User
  ansible.builtin.user:
    name: deluge
    group: "{{ media_group }}"
    shell: /bin/false
    home: /home/bazarr

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ bazarr_yum_packages }}"

- name: Install Deluge Web Service file
  template:
    src: deluge-web.service.j2
    dest: /etc/systemd/system/deluge-web.service

- name: Install Deluge Daemon Service file
  template:
    src: deluged.service.j2
    dest: /etc/systemd/system/deluged.service

- name: Enable Deluge Web
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluge-web

- name: Enable Deluge Daemon
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluged

- name: Add Deluge Port
  community.general.ufw:
    port: 8112
    rule: allow
    proto: tcp
