---

- name: Install Packages
  yum:
    name: mono-locale-extras
    state: latest

- name: Add Radarr User
  user:
    name: radarr
    shell: /sbin/nologin

- name: Create Radarr Dir
  file:
    path: /opt/Radarr
    state: directory
    owner: radarr
    group: radarr

- name: Download radarr
  get_url:
    url: 'https://github.com/Radarr/Radarr/releases/download/v{{ radarr_version }}/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz'
    dest: /tmp
    mode: 0766

- name: Unpack Radarr
  unarchive:
    src: '/tmp/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz'
    group: radarr
    owner: radarr
    dest: /tmp
    extra_opts:
    remote_src: yes
    
- name: Move Radarr Directory
  copy:
    src: /tmp/Radarr/
    dest: /opt/Radarr
    group: radarr
    owner: radarr
    remote_src: yes

- name: Copy Service File
  template:
    src: Radarr.service.j2
    dest: /etc/systemd/system/Radarr.service

- name: Add Radarr Port
  firewalld:
    port: 7878/tcp
    state: enabled
    permanent: yes

- name: Enable Radarr Service
  systemd:
    name: Radarr
    daemon_reload: yes
    enabled: yes
    state: started
  notify: Reload Firewalld

- name: Cleanup Install Files
  file:
    path: '/tmp/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz'
    state: absent
