---

- name: Add Deluge User
  ansible.builtin.user:
    name: deluge
    group: "{{ media_group }}"
    shell: /bin/false
    home: /home/deluge

- name: Create log file directory
  ansible.builtin.file:
    path: /var/log/deluge
    owner: deluge
    group: "{{ media_group }}"
    state: directory
    mode: 0750

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ deluge_apt_packages }}"

- name: Install Deluge Web Service file
  template:
    src: deluge-web.service.j2
    dest: /etc/systemd/system/deluge-web.service

- name: Install Deluge Daemon Service file
  template:
    src: deluged.service.j2
    dest: /etc/systemd/system/deluged.service

- name: Enable Deluge Web
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluge-web

- name: Enable Deluge Daemon
  systemd:
    enabled: yes
    daemon_reload: yes
    state: started
    name: deluged

- name: Add Deluge Port
  community.general.ufw:
    port: 8112
    rule: allow
    proto: tcp
