---

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ bazarr_yum_packages }}"

- name: Add Bazarr User
  ansible.builtin.user:
    name: bazarr
    group: "{{ media_group }}"
    shell: /sbin/nologin

- name: Create Bazarr Dir
  ansible.builtin.file:
    path: "{{ bazarr_dir }}"
    state: directory
    owner: bazarr
    group: "{{ media_group }}"

- name: Download bazarr
  ansible.builtin.get_url:
    url: "{{ bazarr_url }}"
    dest: /tmp
    mode: 0766

- name: Unpack Bazarr
  ansible.builtin.unarchive:
    src: "/tmp/bazarr.zip"
    group: "{{ media_group }}"
    owner: bazarr
    dest: "{{ bazarr_dir }}"
    extra_opts:
    remote_src: yes

- name: Install python requirements
  ansible.builtin.shell: python3 -m pip install -r requirements.txt
  args:
    chdir: "{{ bazarr_dir }}"

- name: Copy Bazarr Service File
  ansible.builtin.template:
    src: bazarr.service.j2
    dest: /etc/systemd/system/bazarr.service

- name: Add Bazarr Port
  community.general.ufw:
    port: 6767
    rule: allow
    proto: tcp

- name: Enable Bazarr Service
  ansible.builtin.systemd:
    name: bazarr
    daemon_reload: yes
    enabled: yes
    state: started
  notify: Reload Firewalld

- name: Cleanup Install Files
  ansible.builtin.file:
    path: "/tmp/bazarr.zip"
    state: absent
