- name: Install Docker Compose
  ansible.builtin.apt:
    name: ['docker-compose', 'gcc', 'python-devel']
    state: present

- name: Install Docker Pip Package
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    extra_args: --ignore-installed PyYAML
  loop:
    - docker
    - docker-compose