---

- name: Install docker compose
  ansible.builtin.shell: sudo curl -L "https://github.com/docker/compose/releases/download/2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Set docker compose bin executable
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: +x