---

bazarr_yum_packages:
  - python3-devel
  - python3-pip
  - python36-distutils-extra

bazarr_url: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip
bazarr_dir: /opt/bazarr

lidarr_user: lidarr
media_group: media
lidarr_version: 0.8.1.2135
