---

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID={{ bazarr_uid }}
      - PGID={{ bazarr_gid }}
      - TZ=America/New_York
    volumes:
      - {{ bazarr_dir }}:/config:rw
      - /Media/Movies:/movies:rw
      - /Media/TV:/tv:rw
    ports:
      - 6767:6767
    restart: unless-stopped
