- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_package | default('docker') }}"
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
