---

name: Ansible Lint Workflow
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@v26.9.0
        with:
          requirements_files: requirements/requirements.yml
